// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Carousel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"carousel-container\"><!-- Feature Cards --><div class=\"carousel-track\"><div class=\"carousel-card card-focused\" id=\"card-0\"><h4 class=\"text-xl font-semibold text-indigo-600\">Personalized News Feed</h4><p class=\"mt-2 text-gray-600\">Get news articles tailored to your interests and reading habits.</p></div><div class=\"carousel-card card-right\" id=\"card-1\"><h4 class=\"text-xl font-semibold text-indigo-600\">Real-time Updates</h4><p class=\"mt-2 text-gray-600\">Stay informed with the latest news as it happens.</p></div><div class=\"carousel-card card-left\" id=\"card-2\"><h4 class=\"text-xl font-semibold text-indigo-600\">Save for Later</h4><p class=\"mt-2 text-gray-600\">Bookmark articles to read at your convenience.</p></div><div class=\"carousel-card card-left\" id=\"card-3\"><h4 class=\"text-xl font-semibold text-indigo-600\">Share with Friends</h4><p class=\"mt-2 text-gray-600\">Easily share interesting articles with your friends.</p></div><div class=\"carousel-card card-left\" id=\"card-4\"><h4 class=\"text-xl font-semibold text-indigo-600\">Customizable Categories</h4><p class=\"mt-2 text-gray-600\">Follow specific categories that interest you the most.</p></div></div><!-- Navigation Buttons --><button class=\"carousel-btn left-btn\" onclick=\"prevSlide()\">&#9665;</button> <button class=\"carousel-btn right-btn\" onclick=\"nextSlide()\">&#9655;</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
