// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"Newsly/internal/utils"
	"Newsly/web/templates/layouts"
	"Newsly/web/templates/partials"
)

func InterestTopics(data utils.InterestTopicsData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen my-10 flex flex-col gap-4 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8\"><h1 class=\"font-bold text-2xl\">Topics:</h1><p>Choose the research topics you're interested in:</p><div id=\"topics-container\" class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for key, item := range data.Categories {
				templ_7745c5c3_Err = partials.InterestTopicCard(key, item.Title, item.Description).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><button id=\"next-button\" hx-trigger=\"click\" hx-post=\"/api/v1/secure/user/interest-topics\" class=\"mt-8 px-4 py-2 bg-blue-500 text-white rounded-md\">Next</button></div><script>\n\t\t\t// Track selected topics in a Set.\n\t\t\tconst selectedTopics = new Set();\n\n\t\t\t// Toggle the visual state and update the Set.\n\t\t\tfunction toggleTopic(el) {\n\t\t\t\tconst topic = el.getAttribute('data-topic');\n\t\t\t\tif (selectedTopics.has(topic)) {\n\t\t\t\t\tselectedTopics.delete(topic);\n\t\t\t\t\tel.classList.remove('selected');\n\t\t\t\t\tel.querySelector('.checkmark').classList.add('hidden');\n\t\t\t\t} else {\n\t\t\t\t\tselectedTopics.add(topic);\n\t\t\t\t\tel.classList.add('selected');\n\t\t\t\t\tel.querySelector('.checkmark').classList.remove('hidden');\n\t\t\t\t}\n\t\t\t}\n\n\t\t\t// Before sending the POST request, attach the selected topics as JSON data.\n\t\t\tdocument.getElementById('next-button').addEventListener('click', function(e) {\n\t\t\t\tconsole.log('Selected topics:', Array.from(selectedTopics));\n\t\t\t\tthis.setAttribute('hx-vals', JSON.stringify({ categories: Array.from(selectedTopics) }));\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Layout(data.BaseData).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
